import sqlite3
conn = sqlite3.connect('MovieRecommendationSystem.db')
cursor = conn.cursor()

movies = [
    
        ("Warfare", 95, "Action", "Alex Garland, Ray Mendoza", "D'Pharaoh Woon-A-Tai, Will Poulter, Cosmo Jarvis", "R", 78, "A platoon of Navy SEALs embark on a dangerous mission in Ramadi, Iraq, with the chaos and brotherhood of war retold through their memories of the event."),
        ("Sinners", 137, "Horror", "Ryan Coogler", "Michael B. Jordan, Jack O'Connell, Hailee Steinfeld", "R", 84, "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back."),
        ("Bring Her Back", 104, "Horror", "Danny Philippou, Michael Philippou", "Billy Barratt, Sally Hawkins, Mischa Heywood", "R", 75, "A brother and sister uncover a terrifying ritual at the secluded home of their new foster mother."),
        ("Mission Impossible: The Final Reckoning", 169, "Action", "Christopher McQuarrie", "Tom Cruise, Hayley Atwell, Ving Rhames", "PG-13", 67, "Hunt and the IMF pursue a dangerous AI called the Entity that's infiltrated global intelligence. With governments and a figure from his past in pursuit, Hunt races to stop it from forever changing the world."),
        ("Thunderbolts*", 127, "Action", "Jake Schreier", "Florence Pugh, Sebastian Stan, Julia Louis-Dreyfus", "PG-13", 68, "After finding themselves ensnared in a death trap, an unconventional team of antiheroes must go on a dangerous mission that will force them to confront the darkest corners of their pasts."),
        ("Black Bag", 93, "Thriller", "Steven Soderbergh", "Michael FassbenderGustaf SkarsgardCate Blanchett", "R", 85, "When intelligence agent Kathryn Woodhouse is suspected of betraying the nation, her husband - also a legendary agent - faces the ultimate test of whether to be loyal to his marriage, or his country."),
        ("One of Them Days", 97, "Comedy", "Lawrence Lamont","Keke Palmer, SZA, Vanessa Bell Calloway", "R", 73, "When best friends and roommates Dreux and Alyssa discover Alyssa's boyfriend has blown their rent money, the duo finds themselves going to extremes in a race against the clock to avoid eviction and keep their friendship intact." ),
        ("The Monkey", 98, "Horror", "Osgood Perkins", "Theo James, Tatiana Maslany, Christian Convery", "R", 62, "When twin brothers Bill and Hal find their father's old monkey toy in the attic, a series of gruesome deaths start. The siblings decide to throw the toy away and move on with their lives, growing apart over the years."),
        ("Companion", 97, "Sci-Fi", "Drew Hancock", "Sophie Thatcher, Jack Quaid, Lukas Gage", "R", 70, "A weekend getaway with friends at a remote cabin turns into chaos after it's revealed that one of the guests is not what they seem."),
        ("The Ritual", 98, "Horror", "David Midell", "Al Pacino, Dan Stevens, Ashley Greene", "N/A", "Two priests, one in crisis with his faith and the other confronting a turbulent past, must overcome their differences to perform a risky exorcism."),
        ("Cleaner", 97, "Thriller", "Martin Campbell", "Poppy Townsend White, Dudley Watts, Calvin Warrington-Heasman", "R", 51, "Criminal activists hijack a gala, taking 300 hostages. One extremist plans mass murder as a message to the world. An Ex-soldier turned window cleaner now works to rescue the hostages."),
        ("Death of a Unicorn", 107, "Horror", "Alex Scharfman", "Paul Rudd, Jenna Ortega, Will Poulter","R", 51, "A father and daughter accidentally hit and kill a unicorn while en route to a weekend retreat, where his billionaire boss seeks to exploit the creature's miraculous curative properties."),
        ("Inheritance", 101, "Thriller", "Neil Burger", "Phoebe Dynevor, Rhys Ifans, Jose Alvarez", "R", 55, "When a young woman learns her father was once a spy, she suddenly finds herself at the center of an international conspiracy."),
        ("Chainsaw Man - The Movie: Reze Arc", 100, "Action", "Tatsuya Yoshihara", "Kikunosuke ToyaShiori IzawaTomori Kusunoki", "R", 71, "A direct sequel to the first season of the series 'Chainsaw Man', featuring Denji, a young man who co-exists with a chainsaw demon. Denji encounters a new romantic interest, but will his involvement place them both in danger?"),
        ("The Fantastic Four: First Steps", 115, "Sci-Fi", "Matt Shakman", "Pedro Pascal, Vanessa Kirby, Ebon Moss-Bachrach", "PG - 13", 65, "Forced to balance their roles as heroes with the strength of their family bond, the Fantastic Four must defend Earth from a ravenous space god called Galactus and his enigmatic herald, the Silver Surfer."),
        ("Superman", 129, "Action", "James Gunn", "David Corenswet, Rachel Brosnahan, Nicholas Hoult", "PG - 13", 68, "Superman must reconcile his alien Kryptonian heritage with his human upbringing as reporter Clark Kent. As the embodiment of truth, justice and the American way he soon finds himself in a world that views these as old-fashioned."),
        ("Happy Gilmore 2", 114, "Comedy", "Kyle Newacheck", "Adam Sandler, Julie Bowen, Christopher McDonald", "PG - 13", 52, "To provide for his family, a retired Happy Gilmore must pick up the golf clubs once more and reconnect with the sport he once dominated."),
        ("How to Train Your Dragon", 125, "Fantasy", "Dean DeBlois", "Mason Thames, Nico Parker, Gerard Butler", "PG", 61, "As an ancient threat endangers both Vikings and dragons alike on the isle of Berk, the friendship between Hiccup, an inventive Viking, and Toothless, a Night Fury dragon, becomes the key to both species forging a new future together.")
        ("Hurry Up Tomorrow", 105, "Thriller", "Trey Edward Shults", "The Weeknd, Jenna Ortega, Barry Keoghan", "R", 29, "An insomniac musician encounters a mysterious stranger, leading to a journey that challenges everything he knows about himself."),
        ("28 Years Later", 115, "Horror", "Danny Boyle", "Jodie Comer, Aaron Taylor-Johnson, Ralph Fiennes","R", 77, "A group of survivors of the rage virus live on a small island. When one of the group leaves the island on a mission into the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors."),
        ("Elio", 98, "Sci-Fi", "Madeline Sharafian, Domee Shi", "Yonas Kibreab, Zoe Saldana, Remy Edgerly", "PG", 66, "Elio, a space fanatic with an active imagination, finds himself on a cosmic misadventure where he must form new bonds with alien lifeforms, navigate a crisis of intergalactic proportions and somehow discover who he is truly meant to be."),
        ("Jurassic World: Rebirth", 133, "Gareth Edwards", "Scarlett Johansson, Mahershala Ali, Jonathan Bailey", "PG - 13", 50, "Five years post-Jurassic World: Dominion (2022), an expedition braves isolated equatorial regions to extract DNA from three massive prehistoric creatures for a groundbreaking medical breakthrough."),
        ("Ballerina", 124, "Len Wiseman", "Ana de Armas, Keanu Reeves, Ian McShane", "R", 59, "An assassin trained in the traditions of the Ruska Roma organization sets out to seek revenge after her father's death."), 
        ("Tron: Ares", 119, "Joachim Ronning", "Jared Leto, Greta Lee, Jeff Bridges", "PG - 13", 48, "A highly sophisticated program, Ares, is sent from the digital world into the real world on a dangerous mission."),
        ("Avatar: Fire and Ash", 197, "James Cameron", "Sam Worthington, Zoe Saldana, Sigourney Weaver", "PG - 13", 61, "Jake and Neytiri's family grapples with grief, encountering a new, aggressive Na'vi tribe, the Ash People, who are led by the fiery Varang, as the conflict on Pandora escalates and a new moral focus emerges."),
        ("M3GAN 2.0", 120, "Gerard Johnstone", "Allison Williams, Violet McGraw, Amie Donald", "PG - 13", 54, "Two years after M3GAN's rampage, her creator, Gemma, resorts to resurrecting her infamous creation in order to take down Amelia, the military-grade weapon who was built by a defense contractor who stole M3GAN's underlying tech."),
        ("Nobody 2", 89, "Action","Timo Tjahjanto", "Bob Odenkirk, Connie Nielsen, Christopher Lloyd", "R", 59, "Suburban dad Hutch Mansell, a former lethal assassin, is pulled back into his violent past after thwarting a home invasion, setting off a chain of events."),
        ("One Battle After Another", 161, "Thriller", "Paul Thomas Anderson", "Leonardo DiCaprio, Sean Penn, Benicio Del Toro", "R", 95, "When their enemy resurfaces after 16 years, a group of ex-revolutionaries reunite to rescue the daughter of one of their own."),
        ("Predator: Badlands", 107, "Sci-Fi", "Dan Trachtenberg", "Elle Fanning, Dimitrius Schuster-Koloamatangi, Ravi Narayan", 71, "A young Predator outcast from his clan finds an unlikely ally on his journey in search of the ultimate adversary."),
        ("The Naked Gun", 85, "Comedy" "Akiva Schaffer", "Liam Neeson, Pamela Anderson, Paul Walter Hauser", 75, "Following in his father's footsteps, a detective works to solve a murder case and save his police department from closure."),
]



#title, duration, genre, director, actors, classification, metascore, concise summary  
#duration is in minutes